name = "stoney-leaderboard"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
# For quick dev. Later, replace "*" with your deployed game origin for stricter CORS.
ALLOW_ORIGIN = "*"

[d1_databases]
[[d1_databases]]
binding = "DB"
database_name = "stoney-db"
# replace with the database_id you get from 'wrangler d1 create'
database_id = "REPLACE_WITH_YOUR_D1_ID"
